### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by SaltedSlark** [thuhcsi/SECap#4]
Hello there,
When I try to test the pretrained model on my own data, I got this error:
```RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [1, 1, 69048, 2]```
any idea to solve it?

**Comment by xuyaoxun** [comment]
It seems that the issue might be due to the input audio having stereo (two channels) format, while the model expects a mono (single channel) input. You can try converting the stereo audio to mono using tools like librosa before feeding it into the model. If this does not resolve the issue, please provide more information.

**Comment by SaltedSlark** [comment]
> It seems that the issue might be due to the input audio having stereo (two channels) format, while the model expects a mono (single channel) input. You can try converting the stereo audio to mono using tools like librosa before feeding it into the model. If this does not resolve the issue, please provide more information.

It works for me! Thank you so much!

**Comment by HeChengHui** [comment]
@xuyaoxun 
I tried using a mono audio of 30s and am getting the following error:
`RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [1, 1, 1319913, 1]`
